version: '2'
services:
  postgres:
    build: ./docker/postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      - POSTGRES_DB=domegis
      - POSTGRES_USER=domegis
      - POSTGRES_PASSWORD=domegis
  redis:
    image: redis:3.2
  domegis:
    build: .
    command: nodemon src/
    ports:
      - 3030:3030
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: development
    volumes:
      - .:/home/node/domegis
      - /home/node/domegis/node_modules
      - /home/node/domegis/bower_components
